### ISSUE TITLE
Run GitLab CI on issue branches

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#878]
In GitLab by @jmorris-uk on Jul 8, 2019, 14:04

Setup GitLab CI to run on any branch for an issue as long as the branch is named

```
issue-
```

Example usage in CI.

```yaml
job:
  # use regexp
  only:
    - /^issue-.*$/
  # use special keyword
  except:
    - branches
```
